-- Item movement ledger for inventory increases.
-- Run in Supabase SQL editor as a privileged role.

create table if not exists public.item_movements (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.items(id) on delete cascade,
  movement_type text not null,
  quantity integer not null,
  from_warehouse text,
  to_warehouse text,
  supplier text,
  return_reason text,
  reference_number text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),

  constraint item_movements_quantity_positive check (quantity > 0),
  constraint item_movements_movement_type_valid check (
    movement_type in ('delivery', 'return', 'transfer')
  ),
  constraint item_movements_from_warehouse_valid check (
    from_warehouse is null or from_warehouse in ('branch_1', 'branch_2', 'branch_3')
  ),
  constraint item_movements_to_warehouse_valid check (
    to_warehouse is null or to_warehouse in ('branch_1', 'branch_2', 'branch_3')
  ),
  constraint item_movements_direction_rules check (
    (
      movement_type in ('delivery', 'return')
      and from_warehouse is null
      and to_warehouse = 'branch_2'
    )
    or
    (
      movement_type = 'transfer'
      and from_warehouse in ('branch_1', 'branch_3')
      and to_warehouse = 'branch_2'
    )
  )
  ,
  constraint item_movements_type_details_rules check (
    (
      movement_type = 'delivery'
      and supplier is not null
      and nullif(trim(supplier), '') is not null
      and return_reason is null
    )
    or
    (
      movement_type = 'return'
      and return_reason is not null
      and nullif(trim(return_reason), '') is not null
      and supplier is null
    )
    or
    (
      movement_type = 'transfer'
      and supplier is null
      and return_reason is null
    )
  )
);

alter table public.item_movements enable row level security;

create or replace function public.set_item_movement_created_by()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.created_by is null then
    new.created_by := auth.uid();
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_item_movement_created_by on public.item_movements;
create trigger trg_set_item_movement_created_by
before insert on public.item_movements
for each row
execute function public.set_item_movement_created_by();

drop policy if exists "item_movements_select_authenticated" on public.item_movements;
drop policy if exists "item_movements_insert_authenticated" on public.item_movements;

create policy "item_movements_select_authenticated"
on public.item_movements
for select
to authenticated
using (true);

create policy "item_movements_insert_authenticated"
on public.item_movements
for insert
to authenticated
with check (auth.uid() is not null);

create index if not exists idx_item_movements_item_id_created_at
  on public.item_movements (item_id, created_at desc);
create index if not exists idx_item_movements_created_at
  on public.item_movements (created_at desc);
create index if not exists idx_item_movements_type_created_at
  on public.item_movements (movement_type, created_at desc);

create or replace view public.item_movements_with_user as
select
  m.*,
  coalesce(
    nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''),
    nullif(trim(u.name), ''),
    u.email,
    m.created_by::text
  ) as created_by_name
from public.item_movements m
left join public.users u on u.id = m.created_by;

alter view public.item_movements_with_user set (security_invoker = true);

grant select on public.item_movements_with_user to authenticated;
